// automake-rs-core: Rule generation
//
// Generates build rules: compile, link, install, check, clean, dist.
// Each rule family gets its own sealed court.
//
// Courts: AM.RULES.COMPILE.1, AM.RULES.LINK.1 — not yet sealed.

/// Categories of rules generated by Automake.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RuleCategory {
    Compile,
    Link,
    Install,
    Uninstall,
    Check,
    Clean,
    Dist,
    DistCheck,
    MaintainerClean,
}

/// A generated make rule.
#[derive(Debug, Clone)]
pub struct MakeRule {
    pub target: String,
    pub dependencies: Vec<String>,
    pub recipe: Vec<String>,
    pub is_phony: bool,
}

/// Rule generator for a specific category.
pub struct RuleGenerator {
    pub category: RuleCategory,
    pub rules: Vec<MakeRule>,
}

impl RuleGenerator {
    pub fn new(category: RuleCategory) -> Self {
        Self {
            category,
            rules: vec![],
        }
    }

    /// Generate rules for this category.
    /// Not yet implemented — court-by-court admission.
    pub fn generate(&mut self) -> Result<&[MakeRule], RuleError> {
        Err(RuleError::NotYetImplemented("rules".to_string()))
    }
}

#[derive(Debug)]
pub enum RuleError {
    NotYetImplemented(String),
    GenerationError(String),
}

impl std::fmt::Display for RuleError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotYetImplemented(s) => write!(f, "not yet implemented: {}", s),
            Self::GenerationError(s) => write!(f, "generation: {}", s),
        }
    }
}

impl std::error::Error for RuleError {}
